@baseUrl = http://localhost:3000

### Create a user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"test 3",
    "email":"test@3.be",
    "password":"12345",
    "passwordConfirm":"12345"
}

### Create a user that allredy existe
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"test 1",
    "email":"test@1.be",
    "password":"azqwazqR",
    "passwordConfirm":"azqwazqR"
}

### Login wrong user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "email":"test@1.be",
    "password":"12346"
}

### Login user 2
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "email":"test@2.be",
    "password":"12345"
}
