@baseUrl = http://localhost:3000

### Create a user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"user3",
    "email":"user3@gmail.com",
    "password":"azqwazqw",
    "passwordConfirm":"azqwazqw"
}

### Login wrong user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "email":"user@gmail.com",
    "password":"azqwazqw"
}

### Login user 3
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "email":"user3@gmail.com",
    "password":"azqwazqw"
}

### Login user 2
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "email":"user2@gmail.com",
    "password":"azqwazqw"
}
