@baseUrl = http://localhost:3000

### Login user 2
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "email":"user2@gmail.com",
    "password":"azqwazqw"
}

### get all influencers
GET {{baseUrl}}/dbUtils/
Content-Type: application/json

### get influencer 00kxxc57xme81j3
GET {{baseUrl}}/dbUtils/00kxxc57xme81j3
