@baseUrl = http://localhost:3000

### Login user 2
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "email":"user2@gmail.com",
    "password":"azqwazqw"
}

### get all influencers
GET {{baseUrl}}/dbUtils/
Content-Type: application/json

### get influencer 1
GET {{baseUrl}}/dbUtils/1
