@baseUrl = http://localhost:3000

### Login user 2
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "email":"user2@gmail.com",
    "password":"azqwazqw"
}

### subscribe to influencer
POST {{baseUrl}}/users/subscribe
Content-Type: application/json

{
    "url":"https://www.twitch.tv/mistermv"
}

### unsubscribe to influencer
POST {{baseUrl}}/users/unsubscribe
Content-Type: application/json

{
    "url":"https://www.twitch.tv/mistermv"
}