@baseUrl = http://localhost:3000

### Login user 3
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "email":"test@3.be",
    "password":"12345"
}

### subscribe to influencer
POST {{baseUrl}}/users/subscribe
Content-Type: application/json

{
    "influencer":"Zerator",
    "platform":"Twiter / X"
}

### unsubscribe to influencer
POST {{baseUrl}}/users/unsubscribe
Content-Type: application/json

{
    "influencer":"Zerator",
    "platform":"Twiter / X"
}

### unsubscribe to influencer
GET {{baseUrl}}/users/
Content-Type: application/json